read_tools v2.0 Added additional tools
Now includes

    selectRead: Select all your read nodes.
    setLocalization: Set localization policy on read nodes only or more.
    setFrameRange: Set start, last, before and after settings on read nodes.
    setError: Set what happens if there's missing frames (on_error) on read nodes.